### ISSUE TITLE
Not working on Solus

### ISSUE THREAD

**Issue by wvpianoman** [gokhanaltun/easy-btrfs#2]
used the cloned ebtrfs and built ebtrfs on my laptop.

└➤  sudo ebtrfs cc root /
sudo: ebtrfs: command not found

└➤  ebtrfs list-config
panic: unable to open database file: no such file or directory

goroutine 1 [running]:
easy-btrfs/database.GetGormSqliteDb()
        /home/brian/github/easy-btrfs/database/gromDB.go:22 +0x1bd
main.main.func2(0x0?)
        /home/brian/github/easy-btrfs/main.go:42 +0x17
github.com/urfave/cli/v2.(*Command).Run.func1()
        /home/brian/go/pkg/mod/github.com/urfave/cli/v2@v2.27.3/command.go:197 +0x37
github.com/urfave/cli/v2.(*Command).Run(0xc00026cb00, 0xc000200900, {0xc000130000, 0x2, 0x2})
        /home/brian/go/pkg/mod/github.com/urfave/cli/v2@v2.27.3/command.go:220 +0x593
github.com/urfave/cli/v2.(*App).RunContext(0xc00018e600, {0x8d24c0, 0xb4a5c0}, {0xc000130000, 0x2, 0x2})
        /home/brian/go/pkg/mod/github.com/urfave/cli/v2@v2.27.3/app.go:333 +0x5a5
github.com/urfave/cli/v2.(*App).Run(...)
        /home/brian/go/pkg/mod/github.com/urfave/cli/v2@v2.27.3/app.go:307
main.main()
        /home/brian/github/easy-btrfs/main.go:70 +0x707

**Comment by gokhanaltun** [comment]
Thank you for the feedback. I will check this.
